=begin
#Argo Workflows API

#Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/

The version of the OpenAPI document: VERSION

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'date'
require 'time'

module ArgoWorkflows
  # CronWorkflowSpec is the specification of a CronWorkflow
  class IoArgoprojWorkflowV1alpha1CronWorkflowSpec
    # ConcurrencyPolicy is the K8s-style concurrency policy that will be used
    attr_accessor :concurrency_policy

    # FailedJobsHistoryLimit is the number of failed jobs to be kept at a time
    attr_accessor :failed_jobs_history_limit

    # Schedule is a schedule to run the Workflow in Cron format
    attr_accessor :schedule

    # StartingDeadlineSeconds is the K8s-style deadline that will limit the time a CronWorkflow will be run after its original scheduled time if it is missed.
    attr_accessor :starting_deadline_seconds

    # SuccessfulJobsHistoryLimit is the number of successful jobs to be kept at a time
    attr_accessor :successful_jobs_history_limit

    # Suspend is a flag that will stop new CronWorkflows from running if set to true
    attr_accessor :suspend

    # Timezone is the timezone against which the cron schedule will be calculated, e.g. \"Asia/Tokyo\". Default is machine's local time.
    attr_accessor :timezone

    attr_accessor :workflow_metadata

    attr_accessor :workflow_spec

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'concurrency_policy' => :'concurrencyPolicy',
        :'failed_jobs_history_limit' => :'failedJobsHistoryLimit',
        :'schedule' => :'schedule',
        :'starting_deadline_seconds' => :'startingDeadlineSeconds',
        :'successful_jobs_history_limit' => :'successfulJobsHistoryLimit',
        :'suspend' => :'suspend',
        :'timezone' => :'timezone',
        :'workflow_metadata' => :'workflowMetadata',
        :'workflow_spec' => :'workflowSpec'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'concurrency_policy' => :'String',
        :'failed_jobs_history_limit' => :'Integer',
        :'schedule' => :'String',
        :'starting_deadline_seconds' => :'Integer',
        :'successful_jobs_history_limit' => :'Integer',
        :'suspend' => :'Boolean',
        :'timezone' => :'String',
        :'workflow_metadata' => :'ObjectMeta',
        :'workflow_spec' => :'IoArgoprojWorkflowV1alpha1WorkflowSpec'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ArgoWorkflows::IoArgoprojWorkflowV1alpha1CronWorkflowSpec` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ArgoWorkflows::IoArgoprojWorkflowV1alpha1CronWorkflowSpec`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'concurrency_policy')
        self.concurrency_policy = attributes[:'concurrency_policy']
      end

      if attributes.key?(:'failed_jobs_history_limit')
        self.failed_jobs_history_limit = attributes[:'failed_jobs_history_limit']
      end

      if attributes.key?(:'schedule')
        self.schedule = attributes[:'schedule']
      end

      if attributes.key?(:'starting_deadline_seconds')
        self.starting_deadline_seconds = attributes[:'starting_deadline_seconds']
      end

      if attributes.key?(:'successful_jobs_history_limit')
        self.successful_jobs_history_limit = attributes[:'successful_jobs_history_limit']
      end

      if attributes.key?(:'suspend')
        self.suspend = attributes[:'suspend']
      end

      if attributes.key?(:'timezone')
        self.timezone = attributes[:'timezone']
      end

      if attributes.key?(:'workflow_metadata')
        self.workflow_metadata = attributes[:'workflow_metadata']
      end

      if attributes.key?(:'workflow_spec')
        self.workflow_spec = attributes[:'workflow_spec']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @schedule.nil?
        invalid_properties.push('invalid value for "schedule", schedule cannot be nil.')
      end

      if @workflow_spec.nil?
        invalid_properties.push('invalid value for "workflow_spec", workflow_spec cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @schedule.nil?
      return false if @workflow_spec.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          concurrency_policy == o.concurrency_policy &&
          failed_jobs_history_limit == o.failed_jobs_history_limit &&
          schedule == o.schedule &&
          starting_deadline_seconds == o.starting_deadline_seconds &&
          successful_jobs_history_limit == o.successful_jobs_history_limit &&
          suspend == o.suspend &&
          timezone == o.timezone &&
          workflow_metadata == o.workflow_metadata &&
          workflow_spec == o.workflow_spec
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [concurrency_policy, failed_jobs_history_limit, schedule, starting_deadline_seconds, successful_jobs_history_limit, suspend, timezone, workflow_metadata, workflow_spec].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = ArgoWorkflows.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
